import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import PageLayout from "../components/layout/PageLayout";
import SEO from "../components/SEO";
import HeroBanner from "../components/ui/HeroBanner";
import Accordion from "../components/ui/Accordion";
import heroBg from "../assets/home/hero-bg.webp";
import { getBreadcrumbSchema, getFAQSchema } from "../seo/schemas";

const guides = {
  "ac-vs-dc-ev-charger-india": {
    title: "AC vs DC EV Chargers in India - Which Do You Need?",
    description: "Clear AC vs DC EV charging guide for India. Power ranges, connectors, home vs public use, and which SpiderEV models fit each job.",
    h1: "AC vs DC EV Chargers in India - A Practical Guide",
    intro: "AC chargers feed the vehicle's onboard charger. DC fast chargers bypass that onboard unit and send power directly to the battery. If vehicles sit for hours, AC is usually the practical choice. If drivers stop briefly and need meaningful range, consider DC.",
    sections: [
      ["What AC charging does", "An AC charge point supplies alternating current to the vehicle. The vehicle's onboard charger converts it to DC for the traction battery, which means the car's onboard limit matters as much as the wallbox rating. A vehicle that accepts 7.4 kW AC will not charge at 22 kW simply because it is connected to a 22 kW post. AC therefore works best where vehicles remain parked for hours: homes, offices, hotels, apartments and destination car parks. Spider Mini and Lite provide 3.3 kW, Smart provides 7.4 kW, Blaze 22 kW, Strike 40 kW and Dash 80 kW across supported multi-vehicle configurations."],
      ["What DC fast charging does", "A DC charger performs power conversion outside the vehicle and supplies controlled DC power to the battery. It bypasses the vehicle's smaller onboard AC converter, which allows substantially higher power for compatible vehicles. This is useful at public sites, highway corridors and fleet depots where drivers cannot leave a vehicle for several hours. The number printed on the cabinet is not a promise of constant charging speed: the vehicle, battery state of charge, temperature, connector, power sharing and site capacity all affect the session."],
      ["Connector cheat sheet", "Type 2 is widely used for AC charging on passenger vehicles. CCS2 combines the Type 2 geometry with additional DC contacts and is a common choice for passenger-car fast charging. CHAdeMO serves compatible legacy and fleet vehicles. IS 17017-2-6 covers supported light-electric-vehicle DC use cases. Always check the exact vehicle inlet before ordering hardware. An adapter or familiar-looking plug is not evidence that the vehicle accepts the charger's protocol, voltage range or power."],
      ["How power changes the site design", "A 3.3 or 7.4 kW home charger may fit an existing residential connection after an electrical assessment. A workplace with several 22 kW bays needs diversity planning because not every vehicle necessarily draws full power at once. A 30 kW or larger DC charger normally needs a dedicated three-phase review, protection coordination and a clear cable route. Higher power can also change the sanctioned-load discussion, transformer requirements and operating tariff. Select the site architecture before treating charger power as a shopping filter."],
      ["Home and apartment decision", "For overnight parking, estimate the energy that must be replaced each day rather than trying to refill the battery from empty. Daily distance, vehicle efficiency and parking hours provide a more useful answer. Confirm the parking allocation, cable route, metering, earthing and society process. Spider Mini, Lite and Smart are the relevant starting points, but the vehicle's AC input limit and the building supply decide whether a larger unit provides any practical benefit."],
      ["Office and destination decision", "At an office, hotel, mall or hospital, vehicles often stay for two to eight hours. AC can serve many bays at lower infrastructure cost than installing a fast charger at every space. The design should consider visitor turnover, employee parking, billing policy and whether chargers need load management through SpiderConnect. Blaze and Strike are useful comparison points for commercial AC requirements; the final number of connectors and power allocation should follow a site study."],
      ["Public, highway and fleet decision", "Public and highway locations need a demand estimate based on vehicle types, arrival pattern and the minutes drivers can wait. A fleet depot adds route schedules and the time vehicles return to base. Spider Fast is the 30 kW entry point for compatible four-wheelers, while Ultra, Surge and Hulk address progressively higher-power corridor and depot roles. Spider Base covers supported light-EV cases. A mixed fleet may need more than one connector or charger type rather than one oversized cabinet."],
      ["Why the advertised kW is not the session average", "EVs change charging power throughout a session. A DC-capable vehicle may accept its highest rate only across part of the battery window, then reduce power as state of charge rises or temperature changes. AC charging is steadier but remains limited by the onboard converter. When comparing chargers, ask what vehicles will use the site and how much energy they need during the available stop. A peak cabinet rating alone cannot predict minutes to full, daily throughput or customer waiting time."],
      ["One fast charger or several slower connectors", "A site budget can sometimes fund one high-power DC gun or several lower-power AC or DC connectors. The better choice depends on arrivals. One fast gun may suit intermittent corridor traffic but creates a queue when two vehicles arrive together. Several lower-power bays may serve a workplace or depot more effectively because vehicles remain parked. Compare simultaneous demand, parking turnover, redundancy and revenue policy. Also confirm whether the electrical connection can support all connectors at their maximum rating or needs managed power sharing."],
      ["Operating cost and tariff questions", "Hardware price is only one part of the decision. Include electrical upgrades, sanctioned-load charges, civil work, cable runs, protection, connectivity, CPMS fees, preventive maintenance and payment operations. Electricity tariff structure can make a high peak expensive even when daily energy sales are modest. Obtain the applicable tariff from the local utility or site bill and model conservative utilisation. Do not use a national average or a best-case session count as the sole basis for selecting AC or DC."],
      ["Access, payments and network management", "Private home charging may use a key, RFID or app-based control depending on the model. Workplaces may need employee access rules and department reporting. Public sites normally need customer discovery, pricing, payments, receipts and remote support. SpiderConnect can manage supported OCPP chargers, but the required integrations and commercial features should be documented before purchase. Decide who owns customer support, tariff changes, refunds and charger monitoring; those operating responsibilities influence the hardware and software scope."],
      ["Common specification mistakes", "Do not compare chargers only by maximum kW. Avoid ordering before confirming the vehicle connector, assuming every CCS2 vehicle accepts the same rate, treating IP protection as permission to ignore drainage, or relying on a general-purpose socket for continuous charging. Do not promise a fixed 20-to-80 percent time without naming the vehicle and conditions. Finally, keep charger supply separate from the complete installed scope so cabling, panels, earthing, civil work, approvals and commissioning are visible in the quotation."],
      ["A simple selection sequence", "First list the vehicles and connector types. Second record how much energy each vehicle uses between visits. Third measure the real parking or turnaround window. Fourth review phase, sanctioned load, transformer capacity, cable route and simultaneous site loads. Fifth decide who can use the charger and whether payment or CPMS reporting is required. Only then compare charger models and installed quotations. This sequence works for a single home bay, an office car park and a fleet depot because it connects hardware power to an actual operating requirement rather than a marketing headline."],
      ["SpiderEV picks by scenario", "Compare Mini and Smart for home use, Blaze and Strike for workplace charging, Fast and above for public four-wheeler sites, and Base for supported two-wheeler fleets. Treat these as starting points, not automatic prescriptions. Before requesting a quote, record the vehicle models, connector inlets, parking duration, daily distance, available phase, sanctioned load, number of simultaneous sessions and whether the site needs paid public access through CPMS."],
    ],
    table: [["Home / overnight", "AC", "Mini, Smart"], ["Office / long dwell", "AC", "Blaze, Strike"], ["Public / short dwell", "DC", "Fast and above"], ["Supported 2W fleet", "DC", "Base"]],
    links: [["See AC range", "/electric-vehicle-ev-ac-charger"], ["See DC range", "/electric-vehicle-ev-dc-charger"], ["About SpiderEV", "/spiderev"]],
    productLinks: [["Spider Mini - 3.3 kW home charging", "/products/ac/spider-mini"], ["Spider Smart - 7.4 kW home wallbox", "/products/ac/spider-smart"], ["Spider Fast - 30 kW public DC", "/products/dc/spider-fast"], ["Spider Base - supported light EVs", "/products/dc/spider-base"]],
    checklist: ["Vehicle models and connector inlets", "Daily kilometres and parking duration", "Available phase and sanctioned load", "Number of simultaneous charging sessions", "Private, fleet or paid-public access", "Cable route, earthing and protection review"],
    faqs: [{ question: "Is DC always better than AC?", answer: "No. AC is often the better fit when a vehicle remains parked for hours. DC is useful when dwell time is short and the vehicle supports fast charging." }, { question: "Can every EV use every connector?", answer: "No. Match the connector and charging standard to the vehicle before selecting hardware." }],
  },
  "home-ev-charger-buying-guide-telangana-andhra": {
    title: "Home EV Charger Guide for Telangana & Andhra Pradesh",
    description: "How to choose a home EV charger in TG & AP: 3.3 vs 7.4 kW, single-phase limits, apartment parking, and SpiderEV Mini, Lite and Smart.",
    h1: "Buying a Home EV Charger in Telangana & Andhra Pradesh",
    intro: "Start with the supply available at the parking bay, the vehicle's AC input limit and the distance driven each day. A larger wallbox does not make the car charge faster than its onboard charger allows.",
    sections: [
      ["Start with the car, not the wallbox", "Find the vehicle's maximum AC input, connector type and usable battery capacity in the manufacturer documentation. A larger charger cannot force the car to accept more than its onboard converter allows. Then estimate the energy used on a normal day. A driver covering 40 to 60 kilometres often needs a top-up rather than a complete refill. This turns the decision from 'how fast can this charger go?' into 'can it replace today's driving before the car leaves tomorrow?'"],
      ["Single-phase reality in many apartments", "Many apartment parking bays use single-phase power. Check the sanctioned load, distribution board, cable route, earthing and society requirements before selecting a charger. Spider Mini and Lite are 3.3 kW options; Spider Smart is 7.4 kW where both the electrical supply and vehicle allow it. Do not assume that an unused socket near the bay is suitable for continuous EV charging. The circuit and protection need to be assessed for the intended load and operating hours."],
      ["3.3 kW vs 7.4 kW with practical examples", "Ignoring losses, a 3.3 kW charger can deliver roughly 26 kWh during an eight-hour parking window, while 7.4 kW can theoretically deliver about 59 kWh in the same time. Actual energy is lower because the vehicle controls the session and charging losses apply. For a 40 kWh battery arriving at 30%, adding 20 kWh may take roughly six to seven hours at 3.3 kW or around three hours at 7.4 kW. These are planning examples, not guaranteed charge times."],
      ["Daily distance matters more than an empty-to-full test", "Suppose the vehicle uses 0.15 kWh per kilometre. A 50-kilometre day consumes about 7.5 kWh before losses, which a 3.3 kW charger can usually replace within an overnight window. A household driving much farther, returning late or operating two EVs may value the shorter recovery time of 7.4 kW. Use the vehicle's real efficiency and schedule for the calculation rather than a generic range claim."],
      ["Permissions, parking and metering", "Confirm that the parking bay is assigned to the resident and identify who approves the cable route through common areas. Ask how electricity will be metered and billed, whether a dedicated circuit is required, and where isolation can be placed. Apartment associations may have their own process and the local electrical requirements can vary. This guide is general planning information, not legal or electrical approval."],
      ["Cable route, earthing and protection", "A long cable run, outdoor exposure or shared distribution board changes the installation scope. The installer should review cable sizing, voltage drop, earthing, residual-current protection, over-current protection, isolation and physical protection for the route. Avoid loose extension leads and general-purpose sockets for sustained charging. The quotation should distinguish the charger price from cabling, civil work, protection devices and any meter or panel changes."],
      ["Spider Mini vs Lite vs Smart", "Choose Mini or Lite when 3.3 kW matches the vehicle, daily energy requirement and available supply. Compare Smart when the car accepts 7.4 kW, the electrical connection supports it and connected control is useful. Review the exact connector and feature list on each product page. The charger name alone does not establish compatibility with every vehicle or property."],
      ["Shared parking and future expansion", "If a building expects several residents to adopt EVs, plan beyond one cable. The association may need a common charging panel, assigned metering and load management so multiple cars do not exceed the building limit. Installing one isolated charger can still be the right first step, but documenting the route and spare capacity makes the next installations easier. SpiderConnect can be considered where connected chargers need common visibility and access rules."],
      ["Time-of-day charging and household load", "Charging after other large household loads have reduced can make better use of the available connection. Record when air conditioners, water heaters, cooking equipment or pumps usually operate, especially if the charger shares the sanctioned load. A connected charger or vehicle scheduler may help move charging into a suitable window, but the schedule should still leave enough time for the required energy. Do not assume an off-peak tariff applies unless it appears in the actual electricity tariff for the connection."],
      ["Solar does not remove the electrical review", "Rooftop solar can offset some charging energy when generation and vehicle parking overlap, but the charger still needs a correctly designed circuit and protection. A car that returns after sunset will normally draw from the grid unless the property has another approved energy arrangement. Compare solar output, household consumption and parking hours before claiming that charging is solar powered. The EV charger should not be sized only from the solar array rating because clouds, seasons and other building loads change available generation."],
      ["How to compare installation quotations", "Ask each quotation to separate the charger model, connector or cable, mounting hardware, cable length, panel changes, protection devices, earthing work, civil work, commissioning, connectivity and warranty. Confirm what happens if the cable route changes after inspection. Compare service response and remote-diagnostics scope as well as price. A low hardware-only quote and a complete installed quote are not equivalent, and an unspecified promise of free installation may exclude the work that the property actually needs."],
      ["After installation", "Keep the circuit labels, warranty information, commissioning record and installer contact details. Learn how to isolate the charger safely and who should be contacted when the vehicle or charger reports a fault. Periodically inspect the cable, plug, mounting and parking area for damage, water ingress or obstruction. If the vehicle changes, verify the new model's connector and input limit before assuming the existing setup is ideal. For shared buildings, retain the metering and approval records for future residents and additional bays."],
      ["When to call an electrician or Spider Energy", "Request an assessment when the cable run is long, the supply is shared, earthing is uncertain, the available load is close to its limit or the property requires formal drawings. Share the vehicle model, parking photographs, approximate cable distance, meter location, phase and sanctioned load. Spider Energy can then compare the appropriate charger and installation scope without relying on an unsupported promise of charging time."],
    ],
    links: [["Get a Mini quote", "/products/ac/spider-mini"], ["Compare Lite", "/products/ac/spider-lite"], ["Compare Smart", "/products/ac/spider-smart"], ["See all AC chargers", "/electric-vehicle-ev-ac-charger"], ["About SpiderEV", "/spiderev"], ["Contact installation team", "/contact-us"]],
    productLinks: [["Spider Mini - 3.3 kW", "/products/ac/spider-mini"], ["Spider Lite - 3.3 kW", "/products/ac/spider-lite"], ["Spider Smart - 7.4 kW", "/products/ac/spider-smart"]],
    checklist: ["Vehicle AC input limit and connector", "Typical daily kilometres", "Hours parked overnight", "Parking allocation and cable route", "Available phase and sanctioned load", "Earthing, protection and metering plan"],
    faqs: [{ question: "Is 3.3 kW enough for daily home charging?", answer: "It can be when daily driving is moderate and the vehicle remains parked overnight. Confirm against the vehicle battery, daily kilometres and available charging window." }, { question: "Can I install a charger in apartment parking?", answer: "It depends on the parking allocation, electrical capacity, cable route and society or property requirements. Review these before installation." }],
  },
};

export default function GuidePage({ slug }) {
  const guide = guides[slug];
  if (!guide) return null;
  const path = `/guides/${slug}`;
  const breadcrumbs = getBreadcrumbSchema([{ name: "Home", url: "/" }, { name: "Guides", url: "/blog" }, { name: guide.h1, url: path }]);
  const article = { "@context": "https://schema.org", "@type": "Article", headline: guide.h1, description: guide.description, mainEntityOfPage: `https://spiderenergy.in${path}`, author: { "@type": "Organization", name: "Spider Energy" }, publisher: { "@id": "https://spiderenergy.in/#organization" }, inLanguage: "en-IN" };
  return (
    <PageLayout>
      <Helmet><title>{guide.title}</title><meta name="description" content={guide.description} /></Helmet>
      <SEO schema={article} schemas={[getFAQSchema(guide.faqs)]} breadcrumbs={breadcrumbs} title={guide.title} description={guide.description} ogType="article" />
      <HeroBanner title={guide.h1} subtitle={guide.intro} bgImage={heroBg} />
      <article className="py-16 sm:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6">
        {guide.table && <div className="overflow-x-auto mb-12"><table className="w-full text-left border-collapse"><thead><tr className="bg-primary text-white"><th className="p-4">Scenario</th><th className="p-4">Typical fit</th><th className="p-4">SpiderEV starting points</th></tr></thead><tbody>{guide.table.map(row => <tr key={row[0]} className="border-b border-gray-200">{row.map(cell => <td key={cell} className="p-4">{cell}</td>)}</tr>)}</tbody></table></div>}
        <div className="space-y-10">{guide.sections.map(([heading, body]) => <section key={heading}><h2 className="text-3xl font-bold text-gray-900">{heading}</h2><p className="mt-4 text-lg leading-relaxed text-gray-600">{body}</p></section>)}</div>
        {guide.productLinks && <section className="mt-12 rounded-2xl bg-gray-50 p-7"><h2 className="text-2xl font-bold">Product pages referenced in this guide</h2><div className="grid sm:grid-cols-2 gap-3 mt-5">{guide.productLinks.map(([label, href]) => <Link key={href} to={href} className="bg-white border border-gray-100 rounded-xl p-4 font-semibold text-primary hover:border-primary">{label} →</Link>)}</div></section>}
        {guide.checklist && <section className="mt-12"><h2 className="text-3xl font-bold">Information to collect before requesting a quote</h2><ul className="grid sm:grid-cols-2 gap-3 mt-5">{guide.checklist.map(item => <li key={item} className="rounded-xl border border-gray-100 p-4 text-gray-700">✓ {item}</li>)}</ul></section>}
        <div className="flex flex-wrap gap-3 mt-12">{guide.links.map(([label, href]) => <Link key={href} to={href} className="bg-primary text-white px-5 py-3 rounded-xl font-semibold">{label}</Link>)}</div>
      </div></article>
      <section className="py-16 bg-gray-50"><div className="max-w-3xl mx-auto px-4"><h2 className="text-3xl font-bold text-center mb-8">Frequently asked questions</h2><Accordion items={guide.faqs} /></div></section>
    </PageLayout>
  );
}
